"use client"
import Header from '@/components/header/Header'
import './globals.css'
import { Roboto } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import AppProvider from '@/context/AppProvider'
import PageChildren from '@/components/children/PageChildren'


const inter = Roboto({ 
  subsets: ['latin'],
  weight:["100","300","400","500","700","900"] 
  })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}





export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {




  return (
    <html lang="en" className="">
      <body className={inter.className}>
          <PageChildren >
            {children}
          </PageChildren>  
      </body>
    </html>
  )
}
